# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tllm.proto\x12\x06server\"\x1e\n\rGetLLMRequest\x12\r\n\x05input\x18\x01 \x01(\t\"\x1c\n\nGetLLMResp\x12\x0e\n\x06output\x18\x01 \x01(\t2C\n\nLLMService\x12\x35\n\x06GetLLM\x12\x15.server.GetLLMRequest\x1a\x12.server.GetLLMResp\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETLLMREQUEST']._serialized_start=21
  _globals['_GETLLMREQUEST']._serialized_end=51
  _globals['_GETLLMRESP']._serialized_start=53
  _globals['_GETLLMRESP']._serialized_end=81
  _globals['_LLMSERVICE']._serialized_start=83
  _globals['_LLMSERVICE']._serialized_end=150
# @@protoc_insertion_point(module_scope)
