// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: llm.proto

// Protobuf Java Version: 3.25.5
package com.uta.javaclient.rpc;

public final class GetLLMServiceProto {
  private GetLLMServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_GetLLMRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_GetLLMRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_GetLLMResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_GetLLMResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tllm.proto\022\006server\"\036\n\rGetLLMRequest\022\r\n\005" +
      "input\030\001 \001(\t\"\034\n\nGetLLMResp\022\016\n\006output\030\001 \001(" +
      "\t2C\n\nLLMService\0225\n\006GetLLM\022\025.server.GetLL" +
      "MRequest\032\022.server.GetLLMResp\"\000B.\n\026com.ut" +
      "a.javaclient.rpcB\022GetLLMServiceProtoP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_server_GetLLMRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_server_GetLLMRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_GetLLMRequest_descriptor,
        new java.lang.String[] { "Input", });
    internal_static_server_GetLLMResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_server_GetLLMResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_GetLLMResp_descriptor,
        new java.lang.String[] { "Output", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
