// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: llm.proto

// Protobuf Java Version: 3.25.5
package com.uta.javaclient.rpc;

public interface GetLLMRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.GetLLMResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string output = 1;</code>
   * @return The output.
   */
  java.lang.String getOutput();
  /**
   * <code>string output = 1;</code>
   * @return The bytes for output.
   */
  com.google.protobuf.ByteString
      getOutputBytes();
}
