// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: llm.proto

// Protobuf Java Version: 3.25.5
package com.uta.javaclient.rpc;

public interface GetLLMRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.GetLLMRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string input = 1;</code>
   * @return The input.
   */
  java.lang.String getInput();
  /**
   * <code>string input = 1;</code>
   * @return The bytes for input.
   */
  com.google.protobuf.ByteString
      getInputBytes();
}
